CXX := g++

CXXFLAGS := -std=c++17 -Wall -Wextra -I./include

TARGET := chainlang.exe

SRCDIR := src
OBJDIR := obj

# Windows libraries required by raylib
LDFLAGS := \
	-lraylib \
	-lopengl32 \
	-lgdi32 \
	-lwinmm \
	-lws2_32 \

SRCS := $(wildcard $(SRCDIR)/*.cpp)
OBJS := $(patsubst $(SRCDIR)/%.cpp,$(OBJDIR)/%.o,$(SRCS))


.PHONY: all build release debug clean


all: build


build: $(TARGET)


$(TARGET): $(OBJS)
	@echo "Linking $(TARGET)..."
	$(CXX) $(CXXFLAGS) $(OBJS) $(LDFLAGS) -o $(TARGET)
	@echo "Build successful!"


$(OBJDIR)/%.o: $(SRCDIR)/%.cpp
	@mkdir -p $(OBJDIR)
	@echo "Compiling $<..."
	$(CXX) $(CXXFLAGS) -c $< -o $@


release: CXXFLAGS += -O2 -DNDEBUG
release: build


debug: CXXFLAGS += -g -O0 -DDEBUG
debug: build


clean:
	rm -rf $(OBJDIR) $(TARGET)

	@echo "Cleaned."